/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#5c4300",
        "primary-container": "#00d1ff",
        "on-tertiary": "#402d00",
        "surface": "#f8fafc",
        "on-tertiary-container": "#654a00",
        "tertiary-container": "#f3b600",
        "surface-container-high": "#f1f5f9",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#e5e1e4",
        "on-primary-fixed": "#001f28",
        "tertiary-fixed-dim": "#fbbc00",
        "on-tertiary-fixed": "#261a00",
        "on-primary-container": "#00566a",
        "surface-dim": "#f1f5f9",
        "secondary-container": "#2ff801",
        "on-error-container": "#ffdad6",
        "surface-variant": "#e2e8f0",
        "outline": "#64748b",
        "inverse-surface": "#131315",
        "background": "#f8fafc",
        "inverse-primary": "#a4e6ff",
        "secondary-fixed-dim": "#095300",
        "secondary-fixed": "#79ff5b",
        "on-error": "#ffffff",
        "primary-fixed": "#004e60",
        "on-surface-variant": "#475569",
        "error-container": "#93000a",
        "on-secondary-container": "#0f6d00",
        "secondary": "#095300",
        "surface-tint": "#00677f",
        "primary": "#00677f",
        "outline-variant": "#cbd5e1",
        "surface-bright": "#ffffff",
        "on-surface": "#1e293b",
        "tertiary-fixed": "#ffdfa0",
        "tertiary": "#854d0e",
        "surface-container-highest": "#e2e8f0",
        "on-background": "#1e293b",
        "surface-container-low": "#f8fafc",
        "on-primary-fixed-variant": "#004e60",
        "primary-fixed-dim": "#4cd6ff",
        "error": "#b91c1c",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#022100",
        "surface-container": "#f1f5f9",
        "on-secondary-fixed-variant": "#095300",
        "on-primary": "#ffffff",
      },
      spacing: {
        xl: "80px",
        sm: "12px",
        md: "24px",
        lg: "48px",
        grid_gutter: "24px",
        base: "8px",
        xs: "4px",
      },
      fontFamily: {
        "body-standard": ["Inter"],
        "mono-code": ["monospace"],
        "label-caps": ["Space Grotesk"],
        "h1-tech": ["Space Grotesk"],
        "display-lg": ["Space Grotesk"],
      },
      fontSize: {
        "body-standard": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "mono-code": ["14px", { lineHeight: "1.5", letterSpacing: "0.05em", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
        "h1-tech": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
